### ISSUE TITLE
Remove ZEN_GREEK, ZEN_CYRILLIC, and ZEN_LINE

### ISSUE THREAD

**Issue by johnnyshields** [gimite/moji#5]
The following are not "zenkaku" characters. It causes issues when working with Greek/Cyrillic text which is not intended to be considered Japanese. I think these should be removed.

```
    ZEN_GREEK => /[Α-Ωα-ω]/,
    ZEN_CYRILLIC => /[А-Яа-я]/,
```

**Comment by gimite** [comment]
Thanks for the feedback. This library is, as you can guess from its name, designed to process text mainly written in Japanese. In context of Japanese, Greek and Cyrillic letters have traditionally been considered Zenkaku. See e.g., https://ja.wikipedia.org/wiki/%E5%85%A8%E8%A7%92%E3%81%A8%E5%8D%8A%E8%A7%92 for background. So this is by design.

The library also provides finer-grained character types and the methods can take target character types as a parameter. So you can exclude Greek and Cyrillic letters from the target if it is the requirement of your application. Also, if you want a more international solution, not just Japanese, I recommend using a library handling Unicode and use its East_Asian_Width attribute.

**Comment by johnnyshields** [comment]
I don't understand. Characters such as `Ω` are not zenkaku (double-width) characters. At a minimum, they should be renamed to HAN_GREEK / HAN_CYRILLIC
